spring.application.name=taskpilot

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5:3b
spring.ai.ollama.chat.options.temperature=0.2
spring.ai.ollama.chat.options.num-predict=512
